# Generated by Django 6.0.3 on 2026-04-21 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('simulated', 'Simulated'), ('published', 'Published')], default='pending', max_length=10)),
                ('winning_numbers', models.JSONField(blank=True, null=True)),
                ('jackpot_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('5', '5-Number Match'), ('4', '4-Number Match'), ('3', '3-Number Match')], max_length=1)),
                ('prize_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proof_image', models.ImageField(blank=True, upload_to='proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draws.draw')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
